site_name: MM-DOCS
site_url: https://majkinetor.github.io/mm-docs-template/
site_description: MM-DOCS Template
site_author: majkinetor
copyright: © majkinetor 2019

repo_url: https://github.com/majkinetor/mm-docs-template
edit_uri: edit/master/source/docs

dev_addr: 0.0.0.0:8000

theme:
    name: material
    palette:
        primary: White
    features:
        - navigation.expand
        - navigation.instant

extra_css:
    - _css/extra.css
    - _css/pdf.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra:
    url_prefix: !!python/object/apply:os.getenv ["MM_DOCS_URL_PREFIX"]
    version: 0.1
    company:
        name: Acme

# https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
markdown_extensions:
    # PyMdown extensions: https://python-markdown.github.io/extensions
    - toc:
        permalink: ↵
    - admonition
    - footnotes
    - codehilite
    - meta
    - abbr
    - sane_lists
    - def_list
    - attr_list
    - tables

    # PyMdown Extensions extensions: https://facelessuser.github.io/pymdown-extensions/
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.superfences
    - pymdownx.smartsymbols
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.keys
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.arithmatex

    # Extra extensions
    - markdown_include.include:
        base_path: inc
    - plantuml_markdown:
        cachedir: __pycache__

    - mdx_custom_span_class

plugins:
    - search:
        language: en    # https://squidfunk.github.io/mkdocs-material/getting-started/#language
    - exclude:
        glob: _*.md
    - pdf-export:
        verbose: false
        media_type: print
        enabled_if_env: MM_DOCS_ENABLE_PDF_EXPORT
        combined: false
    - macros:
        include_dir: inc
nav:
- Home: index.md
- Demonstration: demo.md
- Variables: vars.md
- Revision: revision.md
