site_name: MM-DOCS
site_description: MM-DOCS Template
site_author: majkinetor
copyright: © majkinetor 2019

repo_url: https://github.com/majkinetor/mm-docs-template
edit_uri: edit/master/source/docs

dev_addr: 0.0.0.0:8000

theme:
    custom_dir: overrides
    features:
        - navigation.expand
        - navigation.instant
        - navigation.top
        - navigation.indexes
        - navigation.footer
        - content.action.edit
        - search.highlight
        - search.suggest
    name: material
    palette:
        - scheme: default
          toggle:
              icon: material/lightbulb-outline
              name: Switch to dark mode
        - scheme: slate
          toggle:
              icon: material/lightbulb
              name: Switch to light mode

extra_css:
  - _extra/css/extra.css
  - _extra/css/pdf.css

extra_javascript:
  - _extra/js/mathjax.js
  - _extra/js/tablesort.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js


extra:
    url_prefix: !ENV MM_DOCS_URL_PREFIX
    version: 0.1
    # date format: '%d.%m.%Y %H:%M'
    company:
        name: Acme
    social:
    - icon: dummy value to show social override

# https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
markdown_extensions:
    # PyMdown extensions: https://python-markdown.github.io/extensions
    - toc:
        permalink: ↵
    - abbr
    - admonition
    - attr_list
    - codehilite
    - def_list
    - footnotes
    - md_in_html
    - meta
    - sane_lists
    - tables

    # PyMdown Extensions extensions: https://facelessuser.github.io/pymdown-extensions/
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.smartsymbols
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

    # Extra extensions
    - markdown_include.include:
        base_path: inc
    - plantuml_markdown:
        cachedir: __pycache__

plugins:
    - search:
        lang: en    # https://squidfunk.github.io/mkdocs-material/getting-started/#language
nav:
- Home: index.md
- Demonstration: demo.md
- Extra:
    - Variables: vars.md
    - Revision: revision.md
- Download: download.md
